# Generated by Django 4.1.7 on 2023-03-28 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "studyFluence",
            "0002_answer_question_delete_appuser_answer_question_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.TextField()),
                ("age", models.TextField()),
                ("location", models.TextField()),
                ("firstLanguage", models.TextField()),
                ("highestLevelofEducation", models.TextField()),
                ("importanceOfTutionCost", models.TextField()),
                ("afterLearningLocation", models.TextField()),
                ("afterLearningPlan", models.TextField()),
                ("financialPlan", models.TextField()),
                ("budget", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
